ALTER TABLE usage_logs
ADD COLUMN IF NOT EXISTS auto_checked_out BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS usage_duration_minutes INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_adjusted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_notified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS admin_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
