-- 1. 学生キャッシュテーブル
CREATE TABLE IF NOT EXISTS users_cache (
    student_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    class_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 更新日時自動更新用の関数およびトリガー
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_users_cache_modtime ON users_cache;
CREATE TRIGGER update_users_cache_modtime
    BEFORE UPDATE ON users_cache
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- 2. 利用ログテーブル
CREATE TABLE IF NOT EXISTS usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    class_name VARCHAR(50) NOT NULL,
    checked_in_at TIMESTAMPTZ NOT NULL,
    checked_out_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_usage_logs_student_id ON usage_logs(student_id);
CREATE INDEX IF NOT EXISTS idx_usage_logs_checked_in_at ON usage_logs(checked_in_at);

CREATE INDEX IF NOT EXISTS idx_usage_logs_active_stay 
ON usage_logs(student_id) 
WHERE checked_out_at IS NULL;

-- 自動チェックアウト用の一括更新関数
CREATE OR REPLACE FUNCTION auto_checkout_old_logs(auto_checkout_time_threshold TIMESTAMPTZ)
RETURNS VOID AS $$
BEGIN
    UPDATE usage_logs
    SET checked_out_at = checked_in_at + INTERVAL '15 hours'
    WHERE checked_out_at IS NULL
      AND checked_in_at < auto_checkout_time_threshold;
END;
$$ LANGUAGE plpgsql;