-- ==========================================
-- ジム利用記録システム Supabase スキーマ定義
-- 最終更新: 2026-06-25
-- ==========================================

-- ==========================================
-- 共通: 更新日時自動更新用トリガー関数
-- ==========================================
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


-- ==========================================
-- 1. 学科マスタテーブル (departments_master)
-- ==========================================
CREATE TABLE IF NOT EXISTS departments_master (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    years_count SMALLINT    NOT NULL DEFAULT 2,
    sort_order SMALLINT    NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- updated_at 自動更新トリガー
DROP TRIGGER IF EXISTS update_departments_master_modtime ON departments_master;
CREATE TRIGGER update_departments_master_modtime
    BEFORE UPDATE ON departments_master
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();


-- ==========================================
-- 2. クラスマスタテーブル (department_classes)
--    ※ 旧: class_letter(CHAR 1) → 新: grade(SMALLINT) + class_name(VARCHAR 50)
-- ==========================================

-- 旧カラム class_letter が残っている場合は削除してから再作成
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'department_classes' AND column_name = 'class_letter'
    ) THEN
        -- 旧テーブルを丸ごと再作成（データは一旦破棄 - マスタなので再投入）
        DROP TABLE IF EXISTS department_classes;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS department_classes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT   NOT NULL REFERENCES departments_master(id) ON DELETE CASCADE,
    grade         SMALLINT NOT NULL,
    class_name    VARCHAR(50) NOT NULL,
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(department_id, grade, class_name)
);

CREATE INDEX IF NOT EXISTS idx_department_classes_dept_grade
    ON department_classes(department_id, grade);


-- ==========================================
-- 3. 学生キャッシュテーブル (users_cache)
-- ==========================================
CREATE TABLE IF NOT EXISTS users_cache (
    student_id VARCHAR(50) PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    grade      VARCHAR(20)  NOT NULL,
    class_name VARCHAR(50)  NOT NULL,
    is_staff   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  DEFAULT NOW(),
    updated_at TIMESTAMPTZ  DEFAULT NOW(),
    deleted_at TIMESTAMPTZ  DEFAULT NULL
);

-- カラム追加（既存DBへのマイグレーション対応）
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS is_staff   BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS class_name VARCHAR(50);

-- updated_at 自動更新トリガー
DROP TRIGGER IF EXISTS update_users_cache_modtime ON users_cache;
CREATE TRIGGER update_users_cache_modtime
    BEFORE UPDATE ON users_cache
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- 論理削除されていない有効レコードへの高速アクセス用インデックス
CREATE INDEX IF NOT EXISTS idx_users_cache_active
    ON users_cache(student_id)
    WHERE deleted_at IS NULL;


-- ==========================================
-- 4. 利用ログテーブル (usage_logs)
-- ==========================================
CREATE TABLE IF NOT EXISTS usage_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    department     VARCHAR(100) NOT NULL,
    grade          VARCHAR(20)  NOT NULL,
    class_name     VARCHAR(50)  NOT NULL,
    checked_in_at  TIMESTAMPTZ  NOT NULL,
    checked_out_at TIMESTAMPTZ  DEFAULT NULL,
    created_at     TIMESTAMPTZ  DEFAULT NOW(),
    deleted_at     TIMESTAMPTZ  DEFAULT NULL
);

-- カラム追加（既存DBへのマイグレーション対応）
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS checked_out_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS deleted_at     TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS class_name     VARCHAR(50);

-- 検索高速化インデックス
CREATE INDEX IF NOT EXISTS idx_usage_logs_student_id   ON usage_logs(student_id);
CREATE INDEX IF NOT EXISTS idx_usage_logs_checked_in_at ON usage_logs(checked_in_at);

-- 在室中（チェックアウト未記録・論理削除されていない）レコードの高速検索
CREATE INDEX IF NOT EXISTS idx_usage_logs_checkin_active
    ON usage_logs(student_id, checked_in_at)
    WHERE checked_out_at IS NULL AND deleted_at IS NULL;


-- ==========================================
-- 5. 自動チェックアウト用バッチ関数
--    チェックイン後 15時間を超えた在室中レコードを自動退室
-- ==========================================
CREATE OR REPLACE FUNCTION auto_checkout_old_logs(auto_checkout_time_threshold TIMESTAMPTZ)
RETURNS VOID AS $$
BEGIN
    UPDATE usage_logs
    SET checked_out_at = checked_in_at + INTERVAL '15 hours'
    WHERE checked_out_at IS NULL
      AND deleted_at     IS NULL
      AND checked_in_at  < auto_checkout_time_threshold;
END;
$$ LANGUAGE plpgsql;


-- ==========================================
-- 6. 論理削除レコードの物理削除用バッチ関数
--    削除から30日を超えたレコードを物理削除
-- ==========================================
CREATE OR REPLACE FUNCTION purge_old_deleted_records()
RETURNS VOID AS $$
BEGIN
    DELETE FROM usage_logs
    WHERE deleted_at IS NOT NULL
      AND deleted_at < NOW() - INTERVAL '30 days';

    DELETE FROM users_cache
    WHERE deleted_at IS NOT NULL
      AND deleted_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;
