-- ==========================================
-- ジム利用記録システム Supabase スキーマ定義
-- 最終更新: 2026-07-02
-- ==========================================

-- ==========================================
-- 共通: 更新日時自動更新用トリガー関数
-- ==========================================
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


-- ==========================================
-- 1. 学科マスタテーブル (departments_master)
-- ==========================================
CREATE TABLE IF NOT EXISTS departments_master (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    years_count SMALLINT    NOT NULL DEFAULT 2,
    sort_order SMALLINT    NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

ALTER TABLE departments_master ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;

-- updated_at 自動更新トリガー
DROP TRIGGER IF EXISTS update_departments_master_modtime ON departments_master;
CREATE TRIGGER update_departments_master_modtime
    BEFORE UPDATE ON departments_master
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

CREATE INDEX IF NOT EXISTS idx_departments_master_active
    ON departments_master(sort_order, name)
    WHERE deleted_at IS NULL;


-- ==========================================
-- 2. クラスマスタテーブル (department_classes)
--    ※ 旧: class_letter(CHAR 1) → 新: grade(SMALLINT) + class_name(VARCHAR 50)
-- ==========================================

-- 旧カラム class_letter が残っている場合は削除してから再作成
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'department_classes' AND column_name = 'class_letter'
    ) THEN
        -- 旧テーブルを丸ごと再作成（データは一旦破棄 - マスタなので再投入）
        DROP TABLE IF EXISTS department_classes;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS department_classes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT   NOT NULL REFERENCES departments_master(id) ON DELETE CASCADE,
    grade         SMALLINT NOT NULL,
    class_name    VARCHAR(50) NOT NULL,
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ DEFAULT NULL,
    UNIQUE(department_id, grade, class_name)
);

ALTER TABLE department_classes ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_department_classes_dept_grade
    ON department_classes(department_id, grade);

CREATE INDEX IF NOT EXISTS idx_department_classes_active
    ON department_classes(department_id, grade, sort_order)
    WHERE deleted_at IS NULL;


-- ==========================================
-- 3. 学生キャッシュテーブル (users_cache)
-- ==========================================
CREATE TABLE IF NOT EXISTS users_cache (
    student_id VARCHAR(50) PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    grade      VARCHAR(20)  NOT NULL,
    class_name VARCHAR(50)  NOT NULL,
    is_staff   BOOLEAN      NOT NULL DEFAULT FALSE,
    user_type  VARCHAR(20)  NOT NULL DEFAULT 'student',
    created_at TIMESTAMPTZ  DEFAULT NOW(),
    updated_at TIMESTAMPTZ  DEFAULT NOW(),
    deleted_at TIMESTAMPTZ  DEFAULT NULL
);

-- カラム追加（既存DBへのマイグレーション対応）
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS is_staff   BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS class_name VARCHAR(50);
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS user_type  VARCHAR(20) DEFAULT 'student';

UPDATE users_cache
SET user_type = CASE WHEN grade = '教職員' THEN 'staff' ELSE 'student' END
WHERE user_type IS NULL;

ALTER TABLE users_cache ALTER COLUMN user_type SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'users_cache_user_type_check'
          AND conrelid = 'users_cache'::regclass
    ) THEN
        ALTER TABLE users_cache
            ADD CONSTRAINT users_cache_user_type_check
            CHECK (user_type IN ('student', 'staff'));
    END IF;
END $$;

-- updated_at 自動更新トリガー
DROP TRIGGER IF EXISTS update_users_cache_modtime ON users_cache;
CREATE TRIGGER update_users_cache_modtime
    BEFORE UPDATE ON users_cache
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- 論理削除されていない有効レコードへの高速アクセス用インデックス
CREATE INDEX IF NOT EXISTS idx_users_cache_active
    ON users_cache(student_id)
    WHERE deleted_at IS NULL;


-- ==========================================
-- 4. 利用ログテーブル (usage_logs)
-- ==========================================
CREATE TABLE IF NOT EXISTS usage_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    department     VARCHAR(100) NOT NULL,
    grade          VARCHAR(20)  NOT NULL,
    class_name     VARCHAR(50)  NOT NULL,
    user_type      VARCHAR(20)  NOT NULL DEFAULT 'student',
    checked_in_at  TIMESTAMPTZ  NOT NULL,
    checked_out_at TIMESTAMPTZ  DEFAULT NULL,
    auto_checked_out BOOLEAN    NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  DEFAULT NOW(),
    deleted_at     TIMESTAMPTZ  DEFAULT NULL
);

-- カラム追加（既存DBへのマイグレーション対応）
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS checked_out_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS deleted_at     TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS class_name     VARCHAR(50);
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS user_type      VARCHAR(20) DEFAULT 'student';
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS auto_checked_out BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE usage_logs
SET user_type = CASE WHEN grade = '教職員' THEN 'staff' ELSE 'student' END
WHERE user_type IS NULL;

ALTER TABLE usage_logs ALTER COLUMN user_type SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'usage_logs_user_type_check'
          AND conrelid = 'usage_logs'::regclass
    ) THEN
        ALTER TABLE usage_logs
            ADD CONSTRAINT usage_logs_user_type_check
            CHECK (user_type IN ('student', 'staff'));
    END IF;
END $$;

-- 検索高速化インデックス
CREATE INDEX IF NOT EXISTS idx_usage_logs_student_id   ON usage_logs(student_id);
CREATE INDEX IF NOT EXISTS idx_usage_logs_checked_in_at ON usage_logs(checked_in_at);

-- 在室中（チェックアウト未記録・論理削除されていない）レコードの高速検索
CREATE INDEX IF NOT EXISTS idx_usage_logs_checkin_active
    ON usage_logs(student_id, checked_in_at)
    WHERE checked_out_at IS NULL AND deleted_at IS NULL;


-- ==========================================
-- 5. 通知テーブル (notifications)
-- ==========================================
CREATE TABLE IF NOT EXISTS notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(50) NOT NULL,
    usage_log_id    BIGINT REFERENCES usage_logs(id) ON DELETE SET NULL,
    student_number  TEXT,
    department      TEXT,
    grade           TEXT,
    name            TEXT,
    message         TEXT NOT NULL,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    read_at         TIMESTAMPTZ DEFAULT NULL
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS student_number TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS grade TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ DEFAULT NULL;

UPDATE notifications
SET is_read = is_acknowledged
WHERE is_read IS DISTINCT FROM is_acknowledged;

CREATE INDEX IF NOT EXISTS idx_notifications_ack_created
    ON notifications(is_acknowledged, created_at);

CREATE INDEX IF NOT EXISTS idx_notifications_read_created
    ON notifications(is_read, created_at);

CREATE INDEX IF NOT EXISTS idx_notifications_usage_log_id
    ON notifications(usage_log_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_auto_checkout_unique
    ON notifications(usage_log_id, type)
    WHERE usage_log_id IS NOT NULL AND type = 'auto_checkout';



-- Backfill notifications for rows that were already auto-checked out before this feature was added.
INSERT INTO notifications (
    type,
    usage_log_id,
    student_number,
    department,
    grade,
    name,
    message,
    is_read,
    is_acknowledged
)
SELECT
    'auto_checkout',
    logs.id,
    logs.student_id,
    logs.department,
    logs.grade,
    logs.name,
    logs.student_id || ' ' || logs.name || ' さんが15時間経過により自動退室になりました。',
    FALSE,
    FALSE
FROM usage_logs logs
WHERE logs.auto_checked_out = TRUE
  AND logs.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM notifications existing
      WHERE existing.type = 'auto_checkout'
        AND existing.usage_log_id = logs.id
  )
ON CONFLICT DO NOTHING;-- ==========================================
-- 6. 自動チェックアウト用バッチ関数
--    チェックイン後 15時間を超えた在室中レコードを自動退室
-- ==========================================
CREATE OR REPLACE FUNCTION auto_checkout_old_logs(auto_checkout_time_threshold TIMESTAMPTZ)
RETURNS VOID AS $$
BEGIN
    WITH updated_logs AS (
        UPDATE usage_logs
        SET checked_out_at = checked_in_at + INTERVAL '15 hours',
            auto_checked_out = TRUE,
            admin_confirmed = FALSE
        WHERE checked_out_at IS NULL
          AND deleted_at     IS NULL
          AND checked_in_at  < auto_checkout_time_threshold
        RETURNING id, student_id, department, grade, name
    )
    INSERT INTO notifications (
        type,
        usage_log_id,
        student_number,
        department,
        grade,
        name,
        message,
        is_read,
        is_acknowledged
    )
    SELECT
        'auto_checkout',
        id,
        student_id,
        department,
        grade,
        name,
        student_id || ' ' || name || ' さんが15時間経過により自動退室になりました。',
        FALSE,
        FALSE
    FROM updated_logs
    ON CONFLICT DO NOTHING;
END;
$$ LANGUAGE plpgsql;


-- ==========================================
-- 7. 論理削除レコードの物理削除用バッチ関数
--    削除から30日を超えたレコードを物理削除
-- ==========================================
CREATE OR REPLACE FUNCTION purge_old_deleted_records()
RETURNS VOID AS $$
BEGIN
    DELETE FROM usage_logs
    WHERE deleted_at IS NOT NULL
      AND deleted_at < NOW() - INTERVAL '30 days';

    DELETE FROM users_cache
    WHERE deleted_at IS NOT NULL
      AND deleted_at < NOW() - INTERVAL '30 days';

    DELETE FROM department_classes
    WHERE department_id IN (
        SELECT id FROM departments_master
        WHERE deleted_at IS NOT NULL
          AND deleted_at < NOW() - INTERVAL '30 days'
    );

    DELETE FROM departments_master
    WHERE deleted_at IS NOT NULL
      AND deleted_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 8. v3 確定仕様: 自己学習キャッシュ・ランキング統計カラム
--    既存実装互換のため student_id/user_type は維持し、v3 の user_code/role 相当として扱う
-- ==========================================
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS total_usage_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS monthly_usage_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS consecutive_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS last_used_date DATE;
ALTER TABLE users_cache ADD COLUMN IF NOT EXISTS registered_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS usage_duration_minutes INTEGER;
ALTER TABLE usage_logs ADD COLUMN IF NOT EXISTS admin_confirmed BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_users_cache_monthly_usage
    ON users_cache(monthly_usage_minutes DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_users_cache_consecutive_days
    ON users_cache(consecutive_days DESC)
    WHERE deleted_at IS NULL;

-- 月初リセット用。Vercel Cron / Supabase Scheduled Function などから呼び出す。
CREATE OR REPLACE FUNCTION reset_monthly_usage_minutes()
RETURNS VOID AS $$
BEGIN
    UPDATE users_cache
    SET monthly_usage_minutes = 0,
        updated_at = NOW()
    WHERE deleted_at IS NULL;
END;
$$ LANGUAGE plpgsql;
-- ==========================================
-- 9. 年度更新履歴テーブル
--    4月の学生キャッシュ自動進級の二重実行を防止
-- ==========================================
CREATE TABLE IF NOT EXISTS annual_grade_promotions (
    school_year INTEGER PRIMARY KEY,
    promoted_count INTEGER NOT NULL DEFAULT 0,
    deleted_count INTEGER NOT NULL DEFAULT 0,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
